### ISSUE TITLE
Could not parse manifest

### ISSUE THREAD

**Issue by softhack007** [netmindz/WLED-sync#1]
when building starmod in platformio, I'm getting library manager warnings for WLED-sync

> Library Manager: Could not parse manifest -> Expecting value: line 18 column 3 (char 426)
>[....]
> Dependency Graph
> |-- WLED-sync @ 0.14.0+sha.3cde1ba
>[....]
> Warning! Ignoring broken library manifest in D:\ARDUINO_Work\WORK\#ESP32\StarMod_dev\StarMod\.pio\libdeps\esp32dev\WLED-sync

I think its due to this line 

https://github.com/netmindz/WLED-sync/blob/9df6977ea7dddddb6b8e4d5e7753c8e07ec24ce1/library.json#L17

that should read 
```ini 
    "espressif32"
```

(no trailing komma, and "espressif32")

**Comment by netmindz** [comment]
Updated
